// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env.DATABASE_URL || "postgres://11b79d1c5c9418d64fe006300287294068b65f4f45575a8587749a5a28219a76:sk_yJTRW6GJQaERGESxXWc1Q@db.prisma.io:5432/postgres?sslmode=require",
  },
});
