-- AlterTable
ALTER TABLE "Moodboard" ADD COLUMN "viewportX" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "Moodboard" ADD COLUMN "viewportY" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "Moodboard" ADD COLUMN "viewportScale" DOUBLE PRECISION NOT NULL DEFAULT 1;
